# Stage 1: Build the application
FROM maven:3.8.7 as build
WORKDIR /app

# Copy the source code and build the application
COPY . .
RUN mvn package -DskipTests -Dmaven.compiler.source=17 -Dmaven.compiler.target=17

# Stage 2: Run the application
FROM eclipse-temurin:17

# Copy the JAR file from the build stage
COPY --from=build /app/target/*.jar /app.jar

# Expose the port that the application will run on (replace 8080 with your desired port)
EXPOSE 8080

# Start the application
CMD ["java", "-jar", "-Dserver.port=8080", "app.jar"]

# Build stage
#FROM maven:3.8.3-openjdk-11 AS build
#WORKDIR /app
#COPY .mvn/ .mvn
#COPY mvnw pom.xml ./
#
#RUN chmod +x mvnw
#
## Download the Maven dependencies and build the application
#COPY src ./src
#RUN ./mvnw clean package
#
## Runtime stage
#FROM openjdk:11

#WORKDIR /app

# Copy the compiled JAR file from the build stage
#COPY --from=build /app/target/*.jar app.jar

# Expose the port
#EXPOSE 8080

# Define the entry point to run the application
#CMD ["java", "-jar", "app.jar"]
